#include "ClothesSwitcher.hpp"
#if 1

struct Equip_Item {
    int id;
    const char* name;
};

static constexpr std::array<Equip_Item, 800> clothing_items = {
    // Swords (0-99)
    Equip_Item  {BLOOD_BERRY, "Blood Berry"},
    Equip_Item  {TSUBAKI_MK3, "Tsubaki Mk3"},
    Equip_Item  {TSUBAKI_MK1, "Tsubaki Mk1"},
    Equip_Item  {TSUBAKI_MK2, "Tsubaki Mk2"},
    Equip_Item  {SWORD4,     "Sword 4"},
    Equip_Item  {SWORD5,     "Sword 5"},
    Equip_Item  {SWORD6,     "Sword 6"},
    Equip_Item  {SWORD7,     "Sword 7"},
    Equip_Item  {SWORD8,     "Sword 8"},
    Equip_Item  {SWORD9,     "Sword 9"},
    Equip_Item  {SWORD10,    "Sword 10"},
    Equip_Item  {SWORD11,    "Sword 11"},
    Equip_Item  {SWORD12,    "Sword 12"},
    Equip_Item  {SWORD13,    "Sword 13"},
    Equip_Item  {SWORD14,    "Sword 14"},
    Equip_Item  {SWORD15,    "Sword 15"},
    Equip_Item  {SWORD16,    "Sword 16"},
    Equip_Item  {SWORD17,    "Sword 17"},
    Equip_Item  {SWORD18,    "Sword 18"},
    Equip_Item  {SWORD19,    "Sword 19"},
    Equip_Item  {SWORD20,    "Sword 20"},
    Equip_Item  {SWORD21,    "Sword 21"},
    Equip_Item  {SWORD22,    "Sword 22"},
    Equip_Item  {SWORD23,    "Sword 23"},
    Equip_Item  {SWORD24,    "Sword 24"},
    Equip_Item  {SWORD25,    "Sword 25"},
    Equip_Item  {SWORD26,    "Sword 26"},
    Equip_Item  {SWORD27,    "Sword 27"},
    Equip_Item  {SWORD28,    "Sword 28"},
    Equip_Item  {SWORD29,    "Sword 29"},
    Equip_Item  {SWORD30,    "Sword 30"},
    Equip_Item  {SWORD31,    "Sword 31"},
    Equip_Item  {SWORD32,    "Sword 32"},
    Equip_Item  {SWORD33,    "Sword 33"},
    Equip_Item  {SWORD34,    "Sword 34"},
    Equip_Item  {SWORD35,    "Sword 35"},
    Equip_Item  {SWORD36,    "Sword 36"},
    Equip_Item  {SWORD37,    "Sword 37"},
    Equip_Item  {SWORD38,    "Sword 38"},
    Equip_Item  {SWORD39,    "Sword 39"},
    Equip_Item  {SWORD40,    "Sword 40"},
    Equip_Item  {SWORD41,    "Sword 41"},
    Equip_Item  {SWORD42,    "Sword 42"},
    Equip_Item  {SWORD43,    "Sword 43"},
    Equip_Item  {SWORD44,    "Sword 44"},
    Equip_Item  {SWORD45,    "Sword 45"},
    Equip_Item  {SWORD46,    "Sword 46"},
    Equip_Item  {SWORD47,    "Sword 47"},
    Equip_Item  {SWORD48,    "Sword 48"},
    Equip_Item  {SWORD49,    "Sword 49"},
    Equip_Item  {SWORD50,    "Sword 50"},
    Equip_Item  {SWORD51,    "Sword 51"},
    Equip_Item  {SWORD52,    "Sword 52"},
    Equip_Item  {SWORD53,    "Sword 53"},
    Equip_Item  {SWORD54,    "Sword 54"},
    Equip_Item  {SWORD55,    "Sword 55"},
    Equip_Item  {SWORD56,    "Sword 56"},
    Equip_Item  {SWORD57,    "Sword 57"},
    Equip_Item  {SWORD58,    "Sword 58"},
    Equip_Item  {SWORD59,    "Sword 59"},
    Equip_Item  {SWORD60,    "Sword 60"},
    Equip_Item  {SWORD61,    "Sword 61"},
    Equip_Item  {SWORD62,    "Sword 62"},
    Equip_Item  {SWORD63,    "Sword 63"},
    Equip_Item  {SWORD64,    "Sword 64"},
    Equip_Item  {SWORD65,    "Sword 65"},
    Equip_Item  {SWORD66,    "Sword 66"},
    Equip_Item  {SWORD67,    "Sword 67"},
    Equip_Item  {SWORD68,    "Sword 68"},
    Equip_Item  {SWORD69,    "Sword 69"},
    Equip_Item  {SWORD70,    "Sword 70"},
    Equip_Item  {SWORD71,    "Sword 71"},
    Equip_Item  {SWORD72,    "Sword 72"},
    Equip_Item  {SWORD73,    "Sword 73"},
    Equip_Item  {SWORD74,    "Sword 74"},
    Equip_Item  {SWORD75,    "Sword 75"},
    Equip_Item  {SWORD76,    "Sword 76"},
    Equip_Item  {SWORD77,    "Sword 77"},
    Equip_Item  {SWORD78,    "Sword 78"},
    Equip_Item  {SWORD79,    "Sword 79"},
    Equip_Item  {SWORD80,    "Sword 80"},
    Equip_Item  {SWORD81,    "Sword 81"},
    Equip_Item  {SWORD82,    "Sword 82"},
    Equip_Item  {SWORD83,    "Sword 83"},
    Equip_Item  {SWORD84,    "Sword 84"},
    Equip_Item  {SWORD85,    "Sword 85"},
    Equip_Item  {SWORD86,    "Sword 86"},
    Equip_Item  {SWORD87,    "Sword 87"},
    Equip_Item  {SWORD88,    "Sword 88"},
    Equip_Item  {SWORD89,    "Sword 89"},
    Equip_Item  {SWORD90,    "Sword 90"},
    Equip_Item  {SWORD91,    "Sword 91"},
    Equip_Item  {SWORD92,    "Sword 92"},
    Equip_Item  {SWORD93,    "Sword 93"},
    Equip_Item  {SWORD94,    "Sword 94"},
    Equip_Item  {SWORD95,    "Sword 95"},
    Equip_Item  {SWORD96,    "Sword 96"},
    Equip_Item  {SWORD97,    "Sword 97"},
    Equip_Item  {SWORD98,    "Sword 98"},
    Equip_Item  {SWORD99,    "Sword 99"},

    // Glasses (100-199)
    Equip_Item  {GLASSES0,   "SUNFLOWER"},
    Equip_Item  {GLASSES1,   "ORANGE"},
    Equip_Item  {GLASSES2,   "COBALT BLUE"},
    Equip_Item  {GLASSES3,   "DARK GRAY"},
    Equip_Item  {GLASSES4,   "PEONY PURPLE"},
    Equip_Item  {GLASSES5,   "Glasses 5"},
    Equip_Item  {GLASSES6,   "Glasses 6"},
    Equip_Item  {GLASSES7,   "Glasses 7"},
    Equip_Item  {GLASSES8,   "Glasses 8"},
    Equip_Item  {GLASSES9,   "Glasses 9"},
    Equip_Item  {GLASSES10,  "Glasses 10"},
    Equip_Item  {GLASSES11,  "Glasses 11"},
    Equip_Item  {GLASSES12,  "Glasses 12"},
    Equip_Item  {GLASSES13,  "Glasses 13"},
    Equip_Item  {GLASSES14,  "Glasses 14"},
    Equip_Item  {GLASSES15,  "Glasses 15"},
    Equip_Item  {GLASSES16,  "Glasses 16"},
    Equip_Item  {GLASSES17,  "Glasses 17"},
    Equip_Item  {GLASSES18,  "Glasses 18"},
    Equip_Item  {GLASSES19,  "Glasses 19"},
    Equip_Item  {GLASSES20,  "Glasses 20"},
    Equip_Item  {GLASSES21,  "Glasses 21"},
    Equip_Item  {GLASSES22,  "Glasses 22"},
    Equip_Item  {GLASSES23,  "Glasses 23"},
    Equip_Item  {GLASSES24,  "Glasses 24"},
    Equip_Item  {GLASSES25,  "Glasses 25"},
    Equip_Item  {GLASSES26,  "Glasses 26"},
    Equip_Item  {GLASSES27,  "Glasses 27"},
    Equip_Item  {GLASSES28,  "Glasses 28"},
    Equip_Item  {GLASSES29,  "Glasses 29"},
    Equip_Item  {GLASSES30,  "Glasses 30"},
    Equip_Item  {GLASSES31,  "Glasses 31"},
    Equip_Item  {GLASSES32,  "Glasses 32"},
    Equip_Item  {GLASSES33,  "Glasses 33"},
    Equip_Item  {GLASSES34,  "Glasses 34"},
    Equip_Item  {GLASSES35,  "Glasses 35"},
    Equip_Item  {GLASSES36,  "Glasses 36"},
    Equip_Item  {GLASSES37,  "Glasses 37"},
    Equip_Item  {GLASSES38,  "Glasses 38"},
    Equip_Item  {GLASSES39,  "Glasses 39"},
    Equip_Item  {GLASSES40,  "Glasses 40"},
    Equip_Item  {GLASSES41,  "Glasses 41"},
    Equip_Item  {GLASSES42,  "Glasses 42"},
    Equip_Item  {GLASSES43,  "Glasses 43"},
    Equip_Item  {GLASSES44,  "Glasses 44"},
    Equip_Item  {GLASSES45,  "Glasses 45"},
    Equip_Item  {GLASSES46,  "Glasses 46"},
    Equip_Item  {GLASSES47,  "Glasses 47"},
    Equip_Item  {GLASSES48,  "Glasses 48"},
    Equip_Item  {GLASSES49,  "Glasses 49"},
    Equip_Item  {GLASSES50,  "Glasses 50"},
    Equip_Item  {GLASSES51,  "Glasses 51"},
    Equip_Item  {GLASSES52,  "Glasses 52"},
    Equip_Item  {GLASSES53,  "Glasses 53"},
    Equip_Item  {GLASSES54,  "Glasses 54"},
    Equip_Item  {GLASSES55,  "Glasses 55"},
    Equip_Item  {GLASSES56,  "Glasses 56"},
    Equip_Item  {GLASSES57,  "Glasses 57"},
    Equip_Item  {GLASSES58,  "Glasses 58"},
    Equip_Item  {GLASSES59,  "Glasses 59"},
    Equip_Item  {GLASSES60,  "Glasses 60"},
    Equip_Item  {GLASSES61,  "Glasses 61"},
    Equip_Item  {GLASSES62,  "Glasses 62"},
    Equip_Item  {GLASSES63,  "Glasses 63"},
    Equip_Item  {GLASSES64,  "Glasses 64"},
    Equip_Item  {GLASSES65,  "Glasses 65"},
    Equip_Item  {GLASSES66,  "Glasses 66"},
    Equip_Item  {GLASSES67,  "Glasses 67"},
    Equip_Item  {GLASSES68,  "Glasses 68"},
    Equip_Item  {GLASSES69,  "Glasses 69"},
    Equip_Item  {GLASSES70,  "Glasses 70"},
    Equip_Item  {GLASSES71,  "Glasses 71"},
    Equip_Item  {GLASSES72,  "Glasses 72"},
    Equip_Item  {GLASSES73,  "Glasses 73"},
    Equip_Item  {GLASSES74,  "Glasses 74"},
    Equip_Item  {GLASSES75,  "Glasses 75"},
    Equip_Item  {GLASSES76,  "Glasses 76"},
    Equip_Item  {GLASSES77,  "Glasses 77"},
    Equip_Item  {GLASSES78,  "Glasses 78"},
    Equip_Item  {GLASSES79,  "Glasses 79"},
    Equip_Item  {GLASSES80,  "Glasses 80"},
    Equip_Item  {GLASSES81,  "Glasses 81"},
    Equip_Item  {GLASSES82,  "Glasses 82"},
    Equip_Item  {GLASSES83,  "Glasses 83"},
    Equip_Item  {GLASSES84,  "Glasses 84"},
    Equip_Item  {GLASSES85,  "Glasses 85"},
    Equip_Item  {GLASSES86,  "Glasses 86"},
    Equip_Item  {GLASSES87,  "Glasses 87"},
    Equip_Item  {GLASSES88,  "Glasses 88"},
    Equip_Item  {GLASSES89,  "Glasses 89"},
    Equip_Item  {GLASSES90,  "Glasses 90"},
    Equip_Item  {GLASSES91,  "Glasses 91"},
    Equip_Item  {GLASSES92,  "Glasses 92"},
    Equip_Item  {GLASSES93,  "Glasses 93"},
    Equip_Item  {GLASSES94,  "Glasses 94"},
    Equip_Item  {GLASSES95,  "Glasses 95"},
    Equip_Item  {GLASSES96,  "Glasses 96"},
    Equip_Item  {GLASSES97,  "Glasses 97"},
    Equip_Item  {GLASSES98,  "Glasses 98"},
    Equip_Item  {GLASSES99,  "Glasses 99"},

    // Jackets (200-299)
    Equip_Item  {JACKET0,    "RED HOT"},
    Equip_Item  {JACKET1,    "SKELETAL TIGER"},
    Equip_Item  {JACKET2,    "Mt.Fuji"},
    Equip_Item  {JACKET3,    "NATURE"},
    Equip_Item  {JACKET4,    "TIGER"},
    Equip_Item  {JACKET5,    "ZEBRA"},
    Equip_Item  {JACKET6,    "GRIZZLY BEAR"},
    Equip_Item  {JACKET7,    "CRASH STAR"},
    Equip_Item  {JACKET8,    "ROCK SBAJE"},
    Equip_Item  {JACKET9,    "BIZARRE JELLY"},
    Equip_Item  {JACKET10,   "Jacket 10"},
    Equip_Item  {JACKET11,   "Jacket 11"},
    Equip_Item  {JACKET12,   "Jacket 12"},
    Equip_Item  {JACKET13,   "Jacket 13"},
    Equip_Item  {JACKET14,   "Jacket 14"},
    Equip_Item  {JACKET15,   "Jacket 15"},
    Equip_Item  {JACKET16,   "Jacket 16"},
    Equip_Item  {JACKET17,   "Jacket 17"},
    Equip_Item  {JACKET18,   "Jacket 18"},
    Equip_Item  {JACKET19,   "Jacket 19"},
    Equip_Item  {JACKET20,   "Jacket 20"},
    Equip_Item  {JACKET21,   "Jacket 21"},
    Equip_Item  {JACKET22,   "Jacket 22"},
    Equip_Item  {JACKET23,   "Jacket 23"},
    Equip_Item  {JACKET24,   "Jacket 24"},
    Equip_Item  {JACKET25,   "Jacket 25"},
    Equip_Item  {JACKET26,   "Jacket 26"},
    Equip_Item  {JACKET27,   "Jacket 27"},
    Equip_Item  {JACKET28,   "Jacket 28"},
    Equip_Item  {JACKET29,   "Jacket 29"},
    Equip_Item  {JACKET30,   "Jacket 30"},
    Equip_Item  {JACKET31,   "Jacket 31"},
    Equip_Item  {JACKET32,   "Jacket 32"},
    Equip_Item  {JACKET33,   "Jacket 33"},
    Equip_Item  {JACKET34,   "Jacket 34"},
    Equip_Item  {JACKET35,   "Jacket 35"},
    Equip_Item  {JACKET36,   "Jacket 36"},
    Equip_Item  {JACKET37,   "Jacket 37"},
    Equip_Item  {JACKET38,   "Jacket 38"},
    Equip_Item  {JACKET39,   "Jacket 39"},
    Equip_Item  {JACKET40,   "Jacket 40"},
    Equip_Item  {JACKET41,   "Jacket 41"},
    Equip_Item  {JACKET42,   "Jacket 42"},
    Equip_Item  {JACKET43,   "Jacket 43"},
    Equip_Item  {JACKET44,   "Jacket 44"},
    Equip_Item  {JACKET45,   "Jacket 45"},
    Equip_Item  {JACKET46,   "Jacket 46"},
    Equip_Item  {JACKET47,   "Jacket 47"},
    Equip_Item  {JACKET48,   "Jacket 48"},
    Equip_Item  {JACKET49,   "Jacket 49"},
    Equip_Item  {JACKET50,   "Jacket 50"},
    Equip_Item  {JACKET51,   "Jacket 51"},
    Equip_Item  {JACKET52,   "Jacket 52"},
    Equip_Item  {JACKET53,   "Jacket 53"},
    Equip_Item  {JACKET54,   "Jacket 54"},
    Equip_Item  {JACKET55,   "Jacket 55"},
    Equip_Item  {JACKET56,   "Jacket 56"},
    Equip_Item  {JACKET57,   "Jacket 57"},
    Equip_Item  {JACKET58,   "Jacket 58"},
    Equip_Item  {JACKET59,   "Jacket 59"},
    Equip_Item  {JACKET60,   "Jacket 60"},
    Equip_Item  {JACKET61,   "Jacket 61"},
    Equip_Item  {JACKET62,   "Jacket 62"},
    Equip_Item  {JACKET63,   "Jacket 63"},
    Equip_Item  {JACKET64,   "Jacket 64"},
    Equip_Item  {JACKET65,   "Jacket 65"},
    Equip_Item  {JACKET66,   "Jacket 66"},
    Equip_Item  {JACKET67,   "Jacket 67"},
    Equip_Item  {JACKET68,   "Jacket 68"},
    Equip_Item  {JACKET69,   "Jacket 69"},
    Equip_Item  {JACKET70,   "Jacket 70"},
    Equip_Item  {JACKET71,   "Jacket 71"},
    Equip_Item  {JACKET72,   "Jacket 72"},
    Equip_Item  {JACKET73,   "Jacket 73"},
    Equip_Item  {JACKET74,   "Jacket 74"},
    Equip_Item  {JACKET75,   "Jacket 75"},
    Equip_Item  {JACKET76,   "Jacket 76"},
    Equip_Item  {JACKET77,   "Jacket 77"},
    Equip_Item  {JACKET78,   "Jacket 78"},
    Equip_Item  {JACKET79,   "Jacket 79"},
    Equip_Item  {JACKET80,   "Jacket 80"},
    Equip_Item  {JACKET81,   "Jacket 81"},
    Equip_Item  {JACKET82,   "Jacket 82"},
    Equip_Item  {JACKET83,   "Jacket 83"},
    Equip_Item  {JACKET84,   "Jacket 84"},
    Equip_Item  {JACKET85,   "Jacket 85"},
    Equip_Item  {JACKET86,   "Jacket 86"},
    Equip_Item  {JACKET87,   "Jacket 87"},
    Equip_Item  {JACKET88,   "Jacket 88"},
    Equip_Item  {JACKET89,   "Jacket 89"},
    Equip_Item  {JACKET90,   "Jacket 90"},
    Equip_Item  {JACKET91,   "Jacket 91"},
    Equip_Item  {JACKET92,   "Jacket 92"},
    Equip_Item  {JACKET93,   "Jacket 93"},
    Equip_Item  {JACKET94,   "Jacket 94"},
    Equip_Item  {JACKET95,   "Jacket 95"},
    Equip_Item  {JACKET96,   "Jacket 96"},
    Equip_Item  {JACKET97,   "Jacket 97"},
    Equip_Item  {JACKET98,   "Jacket 98"},
    Equip_Item  {JACKET99,   "Jacket 99"},

    // Shoes (300-399)
    Equip_Item  {SHOES0,     "DEFAULT"},
    Equip_Item  {SHOES1,     "BROWN"},
    Equip_Item  {SHOES2,     "RED"},
    Equip_Item  {SHOES3,     "YELLOW"},
    Equip_Item  {SHOES4,     "GREEN"},
    Equip_Item  {SHOES5,     "BLUE"},
    Equip_Item  {SHOES6,     "PURPLE"},
    Equip_Item  {SHOES7,     "PINK"},
    Equip_Item  {SHOES8,     "DESATURATED"},
    Equip_Item  {SHOES9,     "DARKER"},
    Equip_Item  {SHOES10,    "Shoes 10"},
    Equip_Item  {SHOES11,    "Shoes 11"},
    Equip_Item  {SHOES12,    "Shoes 12"},
    Equip_Item  {SHOES13,    "Shoes 13"},
    Equip_Item  {SHOES14,    "Shoes 14"},
    Equip_Item  {SHOES15,    "Shoes 15"},
    Equip_Item  {SHOES16,    "Shoes 16"},
    Equip_Item  {SHOES17,    "Shoes 17"},
    Equip_Item  {SHOES18,    "Shoes 18"},
    Equip_Item  {SHOES19,    "Shoes 19"},
    Equip_Item  {SHOES20,    "Shoes 20"},
    Equip_Item  {SHOES21,    "Shoes 21"},
    Equip_Item  {SHOES22,    "Shoes 22"},
    Equip_Item  {SHOES23,    "Shoes 23"},
    Equip_Item  {SHOES24,    "Shoes 24"},
    Equip_Item  {SHOES25,    "Shoes 25"},
    Equip_Item  {SHOES26,    "Shoes 26"},
    Equip_Item  {SHOES27,    "Shoes 27"},
    Equip_Item  {SHOES28,    "Shoes 28"},
    Equip_Item  {SHOES29,    "Shoes 29"},
    Equip_Item  {SHOES30,    "Shoes 30"},
    Equip_Item  {SHOES31,    "Shoes 31"},
    Equip_Item  {SHOES32,    "Shoes 32"},
    Equip_Item  {SHOES33,    "Shoes 33"},
    Equip_Item  {SHOES34,    "Shoes 34"},
    Equip_Item  {SHOES35,    "Shoes 35"},
    Equip_Item  {SHOES36,    "Shoes 36"},
    Equip_Item  {SHOES37,    "Shoes 37"},
    Equip_Item  {SHOES38,    "Shoes 38"},
    Equip_Item  {SHOES39,    "Shoes 39"},
    Equip_Item  {SHOES40,    "Shoes 40"},
    Equip_Item  {SHOES41,    "Shoes 41"},
    Equip_Item  {SHOES42,    "Shoes 42"},
    Equip_Item  {SHOES43,    "Shoes 43"},
    Equip_Item  {SHOES44,    "Shoes 44"},
    Equip_Item  {SHOES45,    "Shoes 45"},
    Equip_Item  {SHOES46,    "Shoes 46"},
    Equip_Item  {SHOES47,    "Shoes 47"},
    Equip_Item  {SHOES48,    "Shoes 48"},
    Equip_Item  {SHOES49,    "Shoes 49"},
    Equip_Item  {SHOES50,    "Shoes 50"},
    Equip_Item  {SHOES51,    "Shoes 51"},
    Equip_Item  {SHOES52,    "Shoes 52"},
    Equip_Item  {SHOES53,    "Shoes 53"},
    Equip_Item  {SHOES54,    "Shoes 54"},
    Equip_Item  {SHOES55,    "Shoes 55"},
    Equip_Item  {SHOES56,    "Shoes 56"},
    Equip_Item  {SHOES57,    "Shoes 57"},
    Equip_Item  {SHOES58,    "Shoes 58"},
    Equip_Item  {SHOES59,    "Shoes 59"},
    Equip_Item  {SHOES60,    "Shoes 60"},
    Equip_Item  {SHOES61,    "Shoes 61"},
    Equip_Item  {SHOES62,    "Shoes 62"},
    Equip_Item  {SHOES63,    "Shoes 63"},
    Equip_Item  {SHOES64,    "Shoes 64"},
    Equip_Item  {SHOES65,    "Shoes 65"},
    Equip_Item  {SHOES66,    "Shoes 66"},
    Equip_Item  {SHOES67,    "Shoes 67"},
    Equip_Item  {SHOES68,    "Shoes 68"},
    Equip_Item  {SHOES69,    "Shoes 69"},
    Equip_Item  {SHOES70,    "Shoes 70"},
    Equip_Item  {SHOES71,    "Shoes 71"},
    Equip_Item  {SHOES72,    "Shoes 72"},
    Equip_Item  {SHOES73,    "Shoes 73"},
    Equip_Item  {SHOES74,    "Shoes 74"},
    Equip_Item  {SHOES75,    "Shoes 75"},
    Equip_Item  {SHOES76,    "Shoes 76"},
    Equip_Item  {SHOES77,    "Shoes 77"},
    Equip_Item  {SHOES78,    "Shoes 78"},
    Equip_Item  {SHOES79,    "Shoes 79"},
    Equip_Item  {SHOES80,    "Shoes 80"},
    Equip_Item  {SHOES81,    "Shoes 81"},
    Equip_Item  {SHOES82,    "Shoes 82"},
    Equip_Item  {SHOES83,    "Shoes 83"},
    Equip_Item  {SHOES84,    "Shoes 84"},
    Equip_Item  {SHOES85,    "Shoes 85"},
    Equip_Item  {SHOES86,    "Shoes 86"},
    Equip_Item  {SHOES87,    "Shoes 87"},
    Equip_Item  {SHOES88,    "Shoes 88"},
    Equip_Item  {SHOES89,    "Shoes 89"},
    Equip_Item  {SHOES90,    "Shoes 90"},
    Equip_Item  {SHOES91,    "Shoes 91"},
    Equip_Item  {SHOES92,    "Shoes 92"},
    Equip_Item  {SHOES93,    "Shoes 93"},
    Equip_Item  {SHOES94,    "Shoes 94"},
    Equip_Item  {SHOES95,    "Shoes 95"},
    Equip_Item  {SHOES96,    "Shoes 96"},
    Equip_Item  {SHOES97,    "Shoes 97"},
    Equip_Item  {SHOES98,    "Shoes 98"},
    Equip_Item  {SHOES99,    "Shoes 99"},

    // Jeans (400-499)
    Equip_Item {JEANS0,     "TIGERS 510"},
    Equip_Item {JEANS1,     "BLACK MAMBA"},
    Equip_Item {JEANS2,     "KANGAROO"},
    Equip_Item {JEANS3,     "GOSHAWK"},
    Equip_Item {JEANS4,     "LEOPARD"},
    Equip_Item {JEANS5,     "DONKEY"},
    Equip_Item {JEANS6,     "SNAPPING TURTLE"},
    Equip_Item {JEANS7,     "COYOTE"},
    Equip_Item {JEANS8,     "FIREFLY"},
    Equip_Item {JEANS9,     "TOUCAN"},
    Equip_Item {JEANS10,    "ROCK PYTHON"},
    Equip_Item {JEANS11,    "PURE WHITE LOVER"},
    Equip_Item {JEANS12,    "Jeans 12"},
    Equip_Item {JEANS13,    "Jeans 13"},
    Equip_Item {JEANS14,    "Jeans 14"},
    Equip_Item {JEANS15,    "Jeans 15"},
    Equip_Item {JEANS16,    "Jeans 16"},
    Equip_Item {JEANS17,    "Jeans 17"},
    Equip_Item {JEANS18,    "Jeans 18"},
    Equip_Item {JEANS19,    "Jeans 19"},
    Equip_Item {JEANS20,    "Jeans 20"},
    Equip_Item {JEANS21,    "Jeans 21"},
    Equip_Item {JEANS22,    "Jeans 22"},
    Equip_Item {JEANS23,    "Jeans 23"},
    Equip_Item {JEANS24,    "Jeans 24"},
    Equip_Item {JEANS25,    "Jeans 25"},
    Equip_Item {JEANS26,    "Jeans 26"},
    Equip_Item {JEANS27,    "Jeans 27"},
    Equip_Item {JEANS28,    "Jeans 28"},
    Equip_Item {JEANS29,    "Jeans 29"},
    Equip_Item {JEANS30,    "Jeans 30"},
    Equip_Item {JEANS31,    "Jeans 31"},
    Equip_Item {JEANS32,    "Jeans 32"},
    Equip_Item {JEANS33,    "Jeans 33"},
    Equip_Item {JEANS34,    "Jeans 34"},
    Equip_Item {JEANS35,    "Jeans 35"},
    Equip_Item {JEANS36,    "Jeans 36"},
    Equip_Item {JEANS37,    "Jeans 37"},
    Equip_Item {JEANS38,    "Jeans 38"},
    Equip_Item {JEANS39,    "Jeans 39"},
    Equip_Item {JEANS40,    "Jeans 40"},
    Equip_Item {JEANS41,    "Jeans 41"},
    Equip_Item {JEANS42,    "Jeans 42"},
    Equip_Item {JEANS43,    "Jeans 43"},
    Equip_Item {JEANS44,    "Jeans 44"},
    Equip_Item {JEANS45,    "Jeans 45"},
    Equip_Item {JEANS46,    "Jeans 46"},
    Equip_Item {JEANS47,    "Jeans 47"},
    Equip_Item {JEANS48,    "Jeans 48"},
    Equip_Item {JEANS49,    "Jeans 49"},
    Equip_Item {JEANS50,    "Jeans 50"},
    Equip_Item {JEANS51,    "Jeans 51"},
    Equip_Item {JEANS52,    "Jeans 52"},
    Equip_Item {JEANS53,    "Jeans 53"},
    Equip_Item {JEANS54,    "Jeans 54"},
    Equip_Item {JEANS55,    "Jeans 55"},
    Equip_Item {JEANS56,    "Jeans 56"},
    Equip_Item {JEANS57,    "Jeans 57"},
    Equip_Item {JEANS58,    "Jeans 58"},
    Equip_Item {JEANS59,    "Jeans 59"},
    Equip_Item {JEANS60,    "Jeans 60"},
    Equip_Item {JEANS61,    "Jeans 61"},
    Equip_Item {JEANS62,    "Jeans 62"},
    Equip_Item {JEANS63,    "Jeans 63"},
    Equip_Item {JEANS64,    "Jeans 64"},
    Equip_Item {JEANS65,    "Jeans 65"},
    Equip_Item {JEANS66,    "Jeans 66"},
    Equip_Item {JEANS67,    "Jeans 67"},
    Equip_Item {JEANS68,    "Jeans 68"},
    Equip_Item {JEANS69,    "Jeans 69"},
    Equip_Item {JEANS70,    "Jeans 70"},
    Equip_Item {JEANS71,    "Jeans 71"},
    Equip_Item {JEANS72,    "Jeans 72"},
    Equip_Item {JEANS73,    "Jeans 73"},
    Equip_Item {JEANS74,    "Jeans 74"},
    Equip_Item {JEANS75,    "Jeans 75"},
    Equip_Item {JEANS76,    "Jeans 76"},
    Equip_Item {JEANS77,    "Jeans 77"},
    Equip_Item {JEANS78,    "Jeans 78"},
    Equip_Item {JEANS79,    "Jeans 79"},
    Equip_Item {JEANS80,    "Jeans 80"},
    Equip_Item {JEANS81,    "Jeans 81"},
    Equip_Item {JEANS82,    "Jeans 82"},
    Equip_Item {JEANS83,    "Jeans 83"},
    Equip_Item {JEANS84,    "Jeans 84"},
    Equip_Item {JEANS85,    "Jeans 85"},
    Equip_Item {JEANS86,    "Jeans 86"},
    Equip_Item {JEANS87,    "Jeans 87"},
    Equip_Item {JEANS88,    "Jeans 88"},
    Equip_Item {JEANS89,    "Jeans 89"},
    Equip_Item {JEANS90,    "Jeans 90"},
    Equip_Item {JEANS91,    "Jeans 91"},
    Equip_Item {JEANS92,    "Jeans 92"},
    Equip_Item {JEANS93,    "Jeans 93"},
    Equip_Item {JEANS94,    "Jeans 94"},
    Equip_Item {JEANS95,    "Jeans 95"},
    Equip_Item {JEANS96,    "Jeans 96"},
    Equip_Item {JEANS97,    "Jeans 97"},
    Equip_Item {JEANS98,    "Jeans 98"},
    Equip_Item {JEANS99,    "Jeans 99"},

    // Belts (500-599)
    Equip_Item {BELT0,      "LIZARD"},
    Equip_Item {BELT1,      "BLACK BOA"},
    Equip_Item {BELT2,      "SILVER SERPENT"},
    Equip_Item {BELT3,      "SALAMANDER"},
    Equip_Item {BELT4,      "VIPER"},
    Equip_Item {BELT5,      "SANTA DESTROY"},
    Equip_Item {BELT6,      "OPHIDIAN"},
    Equip_Item {BELT7,      "FLOWER"},
    Equip_Item {BELT8,      "METAL SCALE"},
    Equip_Item {BELT9,      "PINK BOMB"},
    Equip_Item {BELT10,     "Belt 10"},
    Equip_Item {BELT11,     "Belt 11"},
    Equip_Item {BELT12,     "Belt 12"},
    Equip_Item {BELT13,     "Belt 13"},
    Equip_Item {BELT14,     "Belt 14"},
    Equip_Item {BELT15,     "Belt 15"},
    Equip_Item {BELT16,     "Belt 16"},
    Equip_Item {BELT17,     "Belt 17"},
    Equip_Item {BELT18,     "Belt 18"},
    Equip_Item {BELT19,     "Belt 19"},
    Equip_Item {BELT20,     "Belt 20"},
    Equip_Item {BELT21,     "Belt 21"},
    Equip_Item {BELT22,     "Belt 22"},
    Equip_Item {BELT23,     "Belt 23"},
    Equip_Item {BELT24,     "Belt 24"},
    Equip_Item {BELT25,     "Belt 25"},
    Equip_Item {BELT26,     "Belt 26"},
    Equip_Item {BELT27,     "Belt 27"},
    Equip_Item {BELT28,     "Belt 28"},
    Equip_Item {BELT29,     "Belt 29"},
    Equip_Item {BELT30,     "Belt 30"},
    Equip_Item {BELT31,     "Belt 31"},
    Equip_Item {BELT32,     "Belt 32"},
    Equip_Item {BELT33,     "Belt 33"},
    Equip_Item {BELT34,     "Belt 34"},
    Equip_Item {BELT35,     "Belt 35"},
    Equip_Item {BELT36,     "Belt 36"},
    Equip_Item {BELT37,     "Belt 37"},
    Equip_Item {BELT38,     "Belt 38"},
    Equip_Item {BELT39,     "Belt 39"},
    Equip_Item {BELT40,     "Belt 40"},
    Equip_Item {BELT41,     "Belt 41"},
    Equip_Item {BELT42,     "Belt 42"},
    Equip_Item {BELT43,     "Belt 43"},
    Equip_Item {BELT44,     "Belt 44"},
    Equip_Item {BELT45,     "Belt 45"},
    Equip_Item {BELT46,     "Belt 46"},
    Equip_Item {BELT47,     "Belt 47"},
    Equip_Item {BELT48,     "Belt 48"},
    Equip_Item {BELT49,     "Belt 49"},
    Equip_Item {BELT50,     "Belt 50"},
    Equip_Item {BELT51,     "Belt 51"},
    Equip_Item {BELT52,     "Belt 52"},
    Equip_Item {BELT53,     "Belt 53"},
    Equip_Item {BELT54,     "Belt 54"},
    Equip_Item {BELT55,     "Belt 55"},
    Equip_Item {BELT56,     "Belt 56"},
    Equip_Item {BELT57,     "Belt 57"},
    Equip_Item {BELT58,     "Belt 58"},
    Equip_Item {BELT59,     "Belt 59"},
    Equip_Item {BELT60,     "Belt 60"},
    Equip_Item {BELT61,     "Belt 61"},
    Equip_Item {BELT62,     "Belt 62"},
    Equip_Item {BELT63,     "Belt 63"},
    Equip_Item {BELT64,     "Belt 64"},
    Equip_Item {BELT65,     "Belt 65"},
    Equip_Item {BELT66,     "Belt 66"},
    Equip_Item {BELT67,     "Belt 67"},
    Equip_Item {BELT68,     "Belt 68"},
    Equip_Item {BELT69,     "Belt 69"},
    Equip_Item {BELT70,     "Belt 70"},
    Equip_Item {BELT71,     "Belt 71"},
    Equip_Item {BELT72,     "Belt 72"},
    Equip_Item {BELT73,     "Belt 73"},
    Equip_Item {BELT74,     "Belt 74"},
    Equip_Item {BELT75,     "Belt 75"},
    Equip_Item {BELT76,     "Belt 76"},
    Equip_Item {BELT77,     "Belt 77"},
    Equip_Item {BELT78,     "Belt 78"},
    Equip_Item {BELT79,     "Belt 79"},
    Equip_Item {BELT80,     "Belt 80"},
    Equip_Item {BELT81,     "Belt 81"},
    Equip_Item {BELT82,     "Belt 82"},
    Equip_Item {BELT83,     "Belt 83"},
    Equip_Item {BELT84,     "Belt 84"},
    Equip_Item {BELT85,     "Belt 85"},
    Equip_Item {BELT86,     "Belt 86"},
    Equip_Item {BELT87,     "Belt 87"},
    Equip_Item {BELT88,     "Belt 88"},
    Equip_Item {BELT89,     "Belt 89"},
    Equip_Item {BELT90,     "Belt 90"},
    Equip_Item {BELT91,     "Belt 91"},
    Equip_Item {BELT92,     "Belt 92"},
    Equip_Item {BELT93,     "Belt 93"},
    Equip_Item {BELT94,     "Belt 94"},
    Equip_Item {BELT95,     "Belt 95"},
    Equip_Item {BELT96,     "Belt 96"},
    Equip_Item {BELT97,     "Belt 97"},
    Equip_Item {BELT98,     "Belt 98"},
    Equip_Item {BELT99,     "Belt 99"},

    // Shirts (600-699)
    Equip_Item {SHIRT0,     "BIZARRE JELLY"},
    Equip_Item {SHIRT1,     "GORGON"},
    Equip_Item {SHIRT2,     "EAT"},
    Equip_Item {SHIRT3,     "YOU SAY PSYCHO"},
    Equip_Item {SHIRT4,     "SNIPER VICTIM"},
    Equip_Item {SHIRT5,     "RADIOACTIVE"},
    Equip_Item {SHIRT6,     "SKULL"},
    Equip_Item {SHIRT7,     "GRASSHOPPER WRESTLING"},
    Equip_Item {SHIRT8,     "VIVA MEXICO"},
    Equip_Item {SHIRT9,     "VIVA LUCHA LIBRE"},
    Equip_Item {SHIRT10,    "NMH 11 BLUE"},
    Equip_Item {SHIRT11,    "NMH 11 RED"},
    Equip_Item {SHIRT12,    "LIGHTNING BOLT"},
    Equip_Item {SHIRT13,    "BLACK SATANS"},
    Equip_Item {SHIRT14,    "SANTA DESTROY TIGERS"},
    Equip_Item {SHIRT15,    "SNAKE HEART"},
    Equip_Item {SHIRT16,    "WGHM 96.6fm"},
    Equip_Item {SHIRT17,    "HEROES MACABRO"},
    Equip_Item {SHIRT18,    "HEAD SPIN"},
    Equip_Item {SHIRT19,    "MOONWALK"},
    Equip_Item {SHIRT20,    "SKULL AND ROSE"},
    Equip_Item {SHIRT21,    "CAT and...?"},
    Equip_Item {SHIRT22,    "TENGU"},
    Equip_Item {SHIRT23,    "NINJA KILLER"},
    Equip_Item {SHIRT24,    "HARA JUKU"},
    Equip_Item {SHIRT25,    "CONTROL DISORDER"},
    Equip_Item {SHIRT26,    "NIGHT OF THE ZOMBIES"},
    Equip_Item {SHIRT27,    "LEOPARD"},
    Equip_Item {SHIRT28,    "680K CAL"},
    Equip_Item {SHIRT29,    "KILLER LODGE"},
    Equip_Item {SHIRT30,    "BARE KNUCKLE"},
    Equip_Item {SHIRT31,    "MIAMI BASS"},
    Equip_Item {SHIRT32,    "PINHOLE KUN"},
    Equip_Item {SHIRT33,    "LOVE TITS"},
    Equip_Item {SHIRT34,    "I LOVE CHAINSAW"},
    Equip_Item {SHIRT35,    "RIDDLE"},
    Equip_Item {SHIRT36,    "MANGA"},
    Equip_Item {SHIRT37,    "ROBODAM"},
    Equip_Item {SHIRT38,    "JAH"},
    Equip_Item {SHIRT39,    "BIG BOOMBOX"},
    Equip_Item {SHIRT40,    "DOGFIGHT YOKOZUNA"},
    Equip_Item {SHIRT41,    "CAT FIGHT"},
    Equip_Item {SHIRT42,    "SAN DIEGO HEROES"},
    Equip_Item {SHIRT43,    "CONFEDERATE FLAG"},
    Equip_Item {SHIRT44,    "TAKA-KEN"},
    Equip_Item {SHIRT45,    "WAR WITHOUT HONOR"},
    Equip_Item {SHIRT46,    "PIMPIN AINT EASY"},
    Equip_Item {SHIRT47,    "RAW MEAT"},
    Equip_Item {SHIRT48,    "STAR RECORD"},
    Equip_Item {SHIRT49,    "RUBBER DISCS"},
    Equip_Item {SHIRT50,    "ANARCHY"},
    Equip_Item {SHIRT51,    "DENKI BOSATSU"},
    Equip_Item {SHIRT52,    "STAR"},
    Equip_Item {SHIRT53,    "PINK BLUE"},
    Equip_Item {SHIRT54,    "ROUTE 666"},
    Equip_Item {SHIRT55,    "KING OF BEETLES"},
    Equip_Item {SHIRT56,    "HOLDUP MAN"},
    Equip_Item {SHIRT57,    "BORING CHILDREN"},
    Equip_Item {SHIRT58,    "FUDO"},
    Equip_Item {SHIRT59,    "MOVIE STAR"},
    Equip_Item {SHIRT60,    "SPARTAN"},
    Equip_Item {SHIRT61,    "THE GREAT MUSTACHE"},
    Equip_Item {SHIRT62,    "BUBBLES"},
    Equip_Item {SHIRT63,    "GIANT SQUID"},
    Equip_Item {SHIRT64,    "HOLLAND"},
    Equip_Item {SHIRT65,    "BRASIL"},
    Equip_Item {SHIRT66,    "RED DEVIL"},
    Equip_Item {SHIRT67,    "YETI"},
    Equip_Item {SHIRT68,    "SHIFTY EYE"},
    Equip_Item {SHIRT69,    "WAVE MOTION"},
    Equip_Item {SHIRT70,    "STRAWBERRY"},
    Equip_Item {SHIRT71,    "CRANBERRY"},
    Equip_Item {SHIRT72,    "TAG TEAM TACO TWIN"},
    Equip_Item {SHIRT73,    "SANTA DESTROY"},
    Equip_Item {SHIRT74,    "STINKIN' BEER"},
    Equip_Item {SHIRT75,    "CROCODILE"},
    Equip_Item {SHIRT76,    "BLUEBERRY"},
    Equip_Item {SHIRT77,    "X-RAY"},
    Equip_Item {SHIRT78,    "THE GREAT MUSTACHE GOLD"},
    Equip_Item {SHIRT79,    "DESTROYMAN"},
    Equip_Item {SHIRT80,    "NO MORE HEROES"},
    Equip_Item {SHIRT81,    "GLASTONBURY"},
    Equip_Item {SHIRT82,    "LOOP"},
    Equip_Item {SHIRT83,    "HIGH SCORE"},
    Equip_Item {SHIRT84,    "SDH FENCING TEAM"},
    Equip_Item {SHIRT85,    "KEINE HELDEN MEHR"},
    Equip_Item {SHIRT86,    "LUCHACO"},
    Equip_Item {SHIRT87,    "FIRE"},
    Equip_Item {SHIRT88,    "GLASTON 1"},
    Equip_Item {SHIRT89,    "GHM"},
    Equip_Item {SHIRT90,    "TORABISU"},
    Equip_Item {SHIRT91,    "GRID"},
    Equip_Item {SHIRT92,    "GLASTON 2"},
    Equip_Item {SHIRT93,    "GLASTON 3"},
    Equip_Item {SHIRT94,    "SUCH IS LIFE"},
    Equip_Item {SHIRT95,    "LOOKER"},
    Equip_Item {SHIRT96,    "NAKED"},
    Equip_Item {SHIRT97,    "TANK TOP WHITE"},
    Equip_Item {SHIRT98,    "TATTOO"},
    Equip_Item {SHIRT99,    "TANK TOP BLACK"},
    Equip_Item {SHIRT100,   "FAMITSU No.01"},
    Equip_Item {SHIRT101,   "FAMITSU No.02"},
    Equip_Item {SHIRT102,   "FAMITSU No.03"},
    Equip_Item {SHIRT103,   "FAMITSU No.04"},
    Equip_Item {SHIRT104,   "FAMITSU No.05"},
    Equip_Item {SHIRT105,   "FAMITSU No.X-1"},
    Equip_Item {SHIRT106,   "FAMITSU No.X-2"},
    Equip_Item {SHIRT107,   "GHM No.01"},
    Equip_Item {SHIRT108,   "GHM No.02"},
    Equip_Item {SHIRT109,   "GHM No.03"},
    Equip_Item {SHIRT110,   "GHM No.04"},
    Equip_Item {SHIRT111,   "GHM No.05"},
    Equip_Item {SHIRT112,   "GHM No.06"},
    Equip_Item {SHIRT113,   "GHM No.07"},
    Equip_Item {SHIRT114,   "GHM No.08"},
    Equip_Item {SHIRT115,   "GHM No.09"},
    Equip_Item {SHIRT116,   "GHM No.10"},
    Equip_Item {SHIRT117,   "GHM No.11"},
    Equip_Item {SHIRT118,   "GHM No.12"},
    Equip_Item {SHIRT119,   "GHM No.13"},
    Equip_Item {SHIRT120,   "GHM No.14"},
    Equip_Item {SHIRT121,   "GHM No.15"},
    Equip_Item {SHIRT122,   "GHM No.16"},
    Equip_Item {SHIRT123,   "GHM No.17"},
    Equip_Item {SHIRT124,   "GHM No.18"},
    Equip_Item {SHIRT125,   "GHM No.19"},
    Equip_Item {SHIRT126,   "GHM No.20"},
    Equip_Item {SHIRT127,   "GHM No.21"},
    Equip_Item {SHIRT128,   "GHM No.22"},
    Equip_Item {SHIRT129,   "GHM No.23"},
    Equip_Item {SHIRT130,   "GHM No.24"},
    Equip_Item {SHIRT131,   "GHM No.25"},
    Equip_Item {SHIRT132,   "GHM No.26"},
    Equip_Item {SHIRT133,   "GHM No.27"},
    Equip_Item {SHIRT134,   "GHM No.28"},
    Equip_Item {SHIRT135,   "GHM No.29"},
    Equip_Item {SHIRT136,   "GHM No.30"},
    Equip_Item {SHIRT137,   "GHM No.31"},
    Equip_Item {SHIRT138,   "GHM No.32"},
    Equip_Item {SHIRT139,   "GHM No.33"},
    Equip_Item {SHIRT140,   "GHM No.34"},
    Equip_Item {SHIRT141,   "GHM No.35"},
    Equip_Item {SHIRT142,   "GHM No.36"},
    Equip_Item {SHIRT143,   "GHM No.37"},
    Equip_Item {SHIRT144,   "GHM No.38"},
    Equip_Item {SHIRT145,   "Shirt 145"},
    Equip_Item {SHIRT146,   "Shirt 146"},
    Equip_Item {SHIRT147,   "Shirt 147"},
    Equip_Item {SHIRT148,   "Shirt 148"},
    Equip_Item {SHIRT149,   "Shirt 149"},
    Equip_Item {SHIRT150,   "Shirt 150"},
    Equip_Item {SHIRT151,   "Shirt 151"},
    Equip_Item {SHIRT152,   "Shirt 152"},
    Equip_Item {SHIRT153,   "Shirt 153"},
    Equip_Item {SHIRT154,   "Shirt 154"},
    Equip_Item {SHIRT155,   "Shirt 155"},
    Equip_Item {SHIRT156,   "Shirt 156"},
    Equip_Item {SHIRT157,   "Shirt 157"},
    Equip_Item {SHIRT158,   "Shirt 158"},
    Equip_Item {SHIRT159,   "Shirt 159"},
    Equip_Item {SHIRT160,   "Shirt 160"},
    Equip_Item {SHIRT161,   "Shirt 161"},
    Equip_Item {SHIRT162,   "Shirt 162"},
    Equip_Item {SHIRT163,   "Shirt 163"},
    Equip_Item {SHIRT164,   "Shirt 164"},
    Equip_Item {SHIRT165,   "Shirt 165"},
    Equip_Item {SHIRT166,   "Shirt 166"},
    Equip_Item {SHIRT167,   "Shirt 167"},
    Equip_Item {SHIRT168,   "Shirt 168"},
    Equip_Item {SHIRT169,   "Shirt 169"},
    Equip_Item {SHIRT170,   "Shirt 170"},
    Equip_Item {SHIRT171,   "Shirt 171"},
    Equip_Item {SHIRT172,   "Shirt 172"},
    Equip_Item {SHIRT173,   "Shirt 173"},
    Equip_Item {SHIRT174,   "Shirt 174"},
    Equip_Item {SHIRT175,   "Shirt 175"},
    Equip_Item {SHIRT176,   "Shirt 176"},
    Equip_Item {SHIRT177,   "Shirt 177"},
    Equip_Item {SHIRT178,   "Shirt 178"},
    Equip_Item {SHIRT179,   "Shirt 179"},
    Equip_Item {SHIRT180,   "Shirt 180"},
    Equip_Item {SHIRT181,   "Shirt 181"},
    Equip_Item {SHIRT182,   "Shirt 182"},
    Equip_Item {SHIRT183,   "Shirt 183"},
    Equip_Item {SHIRT184,   "Shirt 184"},
    Equip_Item {SHIRT185,   "Shirt 185"},
    Equip_Item {SHIRT186,   "Shirt 186"},
    Equip_Item {SHIRT187,   "Shirt 187"},
    Equip_Item {SHIRT188,   "Shirt 188"},
    Equip_Item {SHIRT189,   "Shirt 189"},
    Equip_Item {SHIRT190,   "Shirt 190"},
    Equip_Item {SHIRT191,   "Shirt 191"},
    Equip_Item {SHIRT192,   "Shirt 192"},
    Equip_Item {SHIRT193,   "Shirt 193"},
    Equip_Item {SHIRT194,   "Shirt 194"},
    Equip_Item {SHIRT195,   "Shirt 195"},
    Equip_Item {SHIRT196,   "Shirt 196"},
    Equip_Item {SHIRT197,   "Shirt 197"},
    Equip_Item {SHIRT198,   "Shirt 198"},
    Equip_Item {SHIRT199,   "Shirt 199"},
};

struct ComboInfo {
    const char* label;
    size_t start_idx;
    size_t end_idx;
};

static constexpr std::array<ComboInfo, 7> combo_boxes = {
    ComboInfo {"Sword ##Combo", 0, 100},
    ComboInfo {"Glasses ##Combo", 100, 200},
    ComboInfo {"Jacket ##Combo", 200, 300},
    ComboInfo {"Shoes ##Combo", 300, 400},
    ComboInfo {"Jeans ##Combo", 400, 500},
    ComboInfo {"Belt ##Combo", 500, 600},
    ComboInfo {"Shirt ##Combo", 600, 800}
};

std::optional<std::string> ClothesSwitcher::on_initialize() {
    return Mod::on_initialize();
}

static const Equip_Item* find_room_by_id(int id) {
    auto it = std::find_if(clothing_items.begin(), clothing_items.end(), [id](const Equip_Item& room) { return room.id == id; });
    IM_ASSERT(it != clothing_items.end()); // crash if we passed wrong index
    size_t index = std::distance(clothing_items.begin(), it);
    IM_ASSERT(index > 0);
    return &clothing_items[index];
};

static int find_room_index_by_id(int id) {
    auto it = std::find_if(clothing_items.begin(), clothing_items.end(), [id](const Equip_Item& room) { return room.id == id; });
    IM_ASSERT(it != clothing_items.end()); // crash if we passed wrong index
    size_t index = std::distance(clothing_items.begin(), it);
    // IM_ASSERT(index > 0);
    return index;
};

void ClothesSwitcher::on_draw_ui() {
    if (mHRPc* player = nmh_sdk::get_mHRPc()) {
        std::vector<int> selected_indices(combo_boxes.size(), 0);
        for (size_t i = 0; i < combo_boxes.size(); i++) {
            const auto& combo = combo_boxes[i];
            int playerItem = find_room_index_by_id(player->mPcStatus.equip[i].id);
            if (playerItem >= 0 && playerItem < clothing_items.size()) {
                selected_indices[i] = playerItem - combo.start_idx;
            }
            size_t selected_item_index = combo.start_idx + selected_indices[i];
            if (playerItem >= 0 && playerItem < clothing_items.size() && ImGui::BeginCombo(combo.label, clothing_items[playerItem].name)) {
                for (size_t n = combo.start_idx; n < combo.end_idx && n < clothing_items.size(); n++) {
                    const bool is_selected = (selected_indices[i] == n - combo.start_idx);
                    if (ImGui::Selectable(clothing_items[n].name, is_selected)) {
                        selected_indices[i] = n - combo.start_idx;
                        nmh_sdk::SetEquip((pcItem)clothing_items[n].id, 0);
                    }
                    if (is_selected) {
                        ImGui::SetItemDefaultFocus();
                    }
                }
                ImGui::EndCombo();
            }
        }
    }
}

// during load
//void ClothesSwitcher::on_config_load(const utility::Config &cfg) {}
// during save
//void ClothesSwitcher::on_config_save(utility::Config &cfg) {}
// do something every frame
//void ClothesSwitcher::on_frame() {}
// will show up in debug window, dump ImGui widgets you want here
//void ClothesSwitcher::on_draw_debug_ui() {}
// will show up in main window, dump ImGui widgets you want here
#endif
